# Generated by Django 2.2.9 on 2020-04-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(default=0)),
                ('question_name', models.CharField(default=' ', max_length=20, unique=True)),
                ('question_text', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['question_no'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, unique=True)),
                ('question_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instant_generator.Question')),
            ],
        ),
    ]
