# Generated by Django 2.2.9 on 2020-04-22 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instant_generator', '0002_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Get_Attention', models.CharField(max_length=255)),
                ('Identify_the_Problem_Your_Audience_Have', models.TextField()),
                ('Provide_the_Solution', models.TextField()),
                ('Present_your_Credentials', models.TextField()),
                ('Show_the_Benefits', models.TextField()),
                ('Give_Social_Proof', models.TextField()),
                ('Make_Your_Offer', models.TextField()),
                ('Give_a_Guarantee', models.TextField()),
                ('Inject_Scarcity', models.TextField()),
                ('Call_to_action', models.TextField()),
                ('Give_a_Warning', models.TextField()),
                ('Close_with_a_Reminder', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_request', 'Can view request'), ('can_approve_request', 'Can approve a request')),
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
