# Generated by Django 2.2.9 on 2020-04-24 18:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0003_auto_20200422_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantgenerator',
            name='Identify_the_Problem_Your_Audience_Have',
            field=tinymce.models.HTMLField(),
        ),
    ]
