# Generated by Django 2.2.9 on 2020-04-24 23:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0004_auto_20200424_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instantgenerator',
            options={},
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Call_to_action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Close_with_a_Reminder',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_Social_Proof',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_a_Guarantee',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_a_Warning',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Inject_Scarcity',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Make_Your_Offer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Present_your_Credentials',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Provide_the_Solution',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Show_the_Benefits',
            field=tinymce.models.HTMLField(),
        ),
    ]
