# Generated by Django 2.2.9 on 2020-05-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0005_auto_20200425_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantgenerator',
            name='Identify_the_Problem_Your_Audience_Have',
            field=models.TextField(),
        ),
    ]
