# Generated by Django 2.2.9 on 2020-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0006_auto_20200514_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avarta/default.png', upload_to='profile_pics'),
        ),
    ]
