# Generated by Django 2.2.9 on 2020-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0007_auto_20200514_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar'),
        ),
    ]
