# Generated by Django 2.2.9 on 2020-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0008_auto_20200514_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantgenerator',
            name='Close_with_a_Reminder',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_Social_Proof',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_a_Guarantee',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_a_Warning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Inject_Scarcity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Make_Your_Offer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Present_your_Credentials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Provide_the_Solution',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Show_the_Benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatar/default.png', upload_to='avatar'),
        ),
    ]
