# Generated by Django 2.2.9 on 2020-05-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0010_auto_20200518_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar/default.png', upload_to='avatar'),
        ),
    ]
