# Generated by Django 2.2.9 on 2020-05-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0011_auto_20200518_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
