# Generated by Django 5.2.17 on 2026-10-05 10:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_generator', '0014_auto_20200908_1342'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('bucket', models.BigIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='activation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Close_with_a_Reminder',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_Social_Proof',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_a_Guarantee',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Give_a_Warning',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Identify_the_Problem_Your_Audience_Have',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Inject_Scarcity',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Make_Your_Offer',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Present_your_Credentials',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Provide_the_Solution',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='instantgenerator',
            name='Show_the_Benefits',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='paraphrase',
            name='Article',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatar'),
        ),
        migrations.AddIndex(
            model_name='instantgenerator',
            index=models.Index(fields=['user', '-created_on', '-id'], name='adcopy_user_history'),
        ),
        migrations.AddIndex(
            model_name='paraphrase',
            index=models.Index(fields=['user', '-created_on', '-id'], name='draft_user_history'),
        ),
        migrations.AddConstraint(
            model_name='ratelimitbucket',
            constraint=models.UniqueConstraint(fields=('key', 'bucket'), name='unique_rate_bucket'),
        ),
    ]
