"""
Django settings for toolx project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

import dj_database_url
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import urlparse
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = config('DEBUG', default=False, cast=bool)
SECRET_KEY = config('SECRET_KEY', default='')
if DEBUG and not SECRET_KEY:
    SECRET_KEY = 'local-development-only-never-use-this-secret-in-production'
if not DEBUG and (len(SECRET_KEY) < 50 or len(set(SECRET_KEY)) < 5 or SECRET_KEY.startswith(('insecure-', 'local-development-', 'django-insecure-'))):
    raise ImproperlyConfigured('Set a strong SECRET_KEY of at least 50 characters for production.')
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1' if DEBUG else '', cast=Csv())
if not DEBUG and (not ALLOWED_HOSTS or any(host.startswith('.') or '*' in host or '/' in host or ':' in host or any(char.isspace() for char in host) for host in ALLOWED_HOSTS)):
    raise ImproperlyConfigured('Set ALLOWED_HOSTS to the exact deployment hostnames.')
PUBLIC_ORIGIN = config('PUBLIC_ORIGIN', default='http://localhost:8000' if DEBUG else '').rstrip('/')
origin = urlparse(PUBLIC_ORIGIN)
if origin.scheme not in ('http', 'https') or not origin.hostname or origin.path or origin.query or origin.fragment or origin.username or origin.password or (not DEBUG and origin.scheme != 'https'):
    raise ImproperlyConfigured('PUBLIC_ORIGIN must be the HTTPS origin of your production site.')
try:
    origin.port
except ValueError as error:
    raise ImproperlyConfigured('PUBLIC_ORIGIN has an invalid port.') from error
if not DEBUG and origin.hostname.lower() not in {host.lower() for host in ALLOWED_HOSTS}:
    raise ImproperlyConfigured('PUBLIC_ORIGIN hostname must be included in ALLOWED_HOSTS.')
CSRF_TRUSTED_ORIGINS = [PUBLIC_ORIGIN]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
# This app cannot assert HTTPS ownership of sibling subdomains or opt into browser preload.
SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W021']
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
DATA_UPLOAD_MAX_MEMORY_SIZE = 256 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 64 * 1024
PASSWORD_RESET_TIMEOUT = 3600
EMAIL_TIMEOUT = 10

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'storages',
    'tinymce',
    'instant_generator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'instant_generator.middleware.RateLimitMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'toolx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'toolx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

DATABASE_URL = config('DATABASE_URL', default='')
if not DEBUG and not DATABASE_URL:
    raise ImproperlyConfigured('DATABASE_URL is required for production; SQLite is development-only.')
if DATABASE_URL:
    if not DEBUG and urlparse(DATABASE_URL).scheme not in ('postgres', 'postgresql'):
        raise ImproperlyConfigured('Use PostgreSQL for production.')
    DATABASES['default'] = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}
WHITENOISE_USE_FINDERS = True

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    # '/var/www/static/',
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
if not DEBUG:
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='')
    if not AWS_STORAGE_BUCKET_NAME or not AWS_S3_REGION_NAME:
        raise ImproperlyConfigured('Set AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME for persistent media.')
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default=None)
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default=None)
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default=None)
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'

# Django Crispyform settings
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#  Login Configuration
LOGIN_URL = config('LOGIN_URL', default='/login/')
LOGOUT_URL = config('LOGOUT_URL', default='/logout/')
LOGIN_REDIRECT_URL = config('LOGIN_REDIRECT_URL', default='/dashboard/')
LOGOUT_REDIRECT_URL = config('LOGOUT_REDIRECT_URL', default='/')


# EMAIL_BACKEND During development only
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# # EMAIL_BACKEND production config (Gmail)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
if not DEBUG and (EMAIL_BACKEND != 'django.core.mail.backends.smtp.EmailBackend' or EMAIL_HOST == 'localhost'):
    raise ImproperlyConfigured('Configure an SMTP mail backend and EMAIL_HOST for production activation emails.')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=not DEBUG, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('Use either EMAIL_USE_TLS or EMAIL_USE_SSL, not both.')
if not DEBUG and not (EMAIL_USE_TLS or EMAIL_USE_SSL):
    raise ImproperlyConfigured('Production SMTP must use TLS or SSL.')


# OTHER EMAIL SETTINGS #
########################
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@example.com')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='support@example.com')
if not DEBUG and (not ADMIN_EMAIL or ADMIN_EMAIL == 'admin@example.com'):
    raise ImproperlyConfigured('Set ADMIN_EMAIL to your verified production sender.')
DEFAULT_FROM_EMAIL = ADMIN_EMAIL
SERVER_EMAIL = ADMIN_EMAIL
